# Generated by Django 3.1.3 on 2020-11-17 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='watchlist_users',
            field=models.ManyToManyField(blank=True, related_name='watchlistusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
