# Generated by Django 3.1.3 on 2020-11-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
