# Generated by Django 3.1.3 on 2020-11-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201123_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='auction_category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
